version: "3.8"

services:
  redmine-db:
    image: mariadb
    container_name: redmine-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
    volumes:
      - ./data/mariadb:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - redmine_network

  redmine:
    image: redmine
    container_name: redmine
    ports:
      - 3000:3000
    volumes:
      - ./config.ru:/usr/src/redmine/config.ru:ro
      - ./data/redmine/files:/usr/src/redmine/files
      - ./data/redmine/log:/usr/src/redmine/log
      - ./data/redmine/plugins:/usr/src/redmine/plugins
      - ./data/redmine/public/themes:/usr/src/redmine/public/themes
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_PASSWORD: redmine
      RAILS_RELATIVE_URL_ROOT: /redmine
    depends_on:
      - redmine-db
    networks:
      - shared_network
      - redmine_network

networks:
  shared_network:
    external: true
  redmine_network:
    driver: bridge
